### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by BlayZin** [Phineas05/discord-rich-presence-plex#1] opened 2018-03-08 06:52 UTC
Something is wrong if you have multiple Users on one Plex Server.
I recently updated the Plex Server Version but one User on it was still on Pause on one Video. 
Even though it doesn't show that the Person is watching in the Plex Status log after the Restart, the Script still detects that Person and shows it as my Status.
I even set me as the Specific User to look for. It just takes the other Person anyways.

**Comment by Phineas05** [comment] 2018-03-08 07:12
I've tested it with multiple users and it worked fine when the `listenForUser` variable was set to my username. Are you sure another instance of the script wasn't running where `listenForUser` wasn't set to your username?

**Comment by BlayZin** [comment] 2018-03-08 07:18
No I even restarted my Plex Server again. And edited the Script to use token but I guess that shouldn't change anything anyways.
The Person that is listed doesn't even have his PC running.
I hope there isn't any important information but as soon as I start the script it is stuck here: https://i.imgur.com/kgVOsVn.jpg

**Comment by Phineas05** [comment] 2018-03-08 07:50
I'm not sure what's wrong. I just tested it again with multiple users and the latest Plex Media Server and it still works as intended.

**Comment by BlayZin** [comment] 2018-03-08 08:01
I shared my Library through Friends dunno if that could be the reason.

**Comment by Phineas05** [comment] 2018-03-08 16:37
That shouldn't cause any problems. Looking at your screenshot it should only respond to activity from user "BlayZin". I went through the script to see if I missed something but I can't find anything that could be causing your issue.

**Comment by BlayZin** [comment] 2018-03-09 02:48
Hmm I don't know what happened but it solved itself. I'm gonna observe it if it happens again.

**Comment by BlayZin** [comment] 2018-03-11 17:25
Sorry for opening this again. But it still happens.
So maybe to figure out why it happens I tell you some things.
This is a Feralhosting Server I own where I installed a Plex media Server.
My Account BlayZin claimed this Server so I am the Owner with that account.
I am Friends with one Person and shared my Library with him via Friendlist.
Everytime he watches something it counts as me watching someting (don't know why).
I set up the .py file correct with specifically my Name "BlayZin". 

```
plexServerName = "Kyoko"
plexUsername = "BlayZin"
plexPasswordOrToken = "Password"
usingToken = True
listenForUser = "BlayZin"
listenForUser = plexUsername if listenForUser == "" else listenForUser
```

with or without Token it's the same Issue.

**Comment by Phineas05** [comment] 2018-03-11 19:00
It's fine, I'm curious as to what's causing it and would like to get it fixed if possible. Are you sure that your friend isn't using your account without realizing it? Maybe one of the devices he's using is logged in with your account.

**Comment by BlayZin** [comment] 2018-03-11 19:26
No he doesn't know my info at all.

**Comment by Phineas05** [comment] 2018-03-11 19:54
Does the "Now Playing" page on Plex (`http://yourServerIP/web/index.html#!/status/playing`) display incorrect information when the issue occurs?

**Comment by BlayZin** [comment] 2018-03-11 20:04
I haven't looked at the web version when this happened gonna do that if that happens again but in the app it basically looks like this when it happens: https://i.imgur.com/cpuxXur.png

**Comment by Phineas05** [comment] 2018-03-11 20:10
It'll look the same in the web version. I'm guessing it's working properly right now so check the page again when it isn't and see if it shows your username instead of your friend's username. I also updated the script to make it print out a bunch of extra stuff so update your copy of it and set the `extraLogging` variable on line 19 to `True`.

**Comment by BlayZin** [comment] 2018-03-11 21:08
Will do! Thanks for the Effort!

**Comment by BlayZin** [comment] 2018-03-14 18:36
So I got this again but this Time with extra log on.
Here I watched something and sometime later it boots up again when trader0 starts watching something:
https://i.imgur.com/gLhem8U.png
It basically goes on like this every 5 seconds or so:
https://i.imgur.com/iGFKJiN.png

I hope it helps.

**Comment by Phineas05** [comment] 2018-03-14 19:39
That helps, I see what's wrong. The Plex Server's sessions list seems to be empty sometimes and that causes the script to pass because the loop on sessions that checks the usernames doesn't run when the list to loop through is empty. I added a list length check. Update your copy of the script and it should be fixed.

**Comment by BlayZin** [comment] 2018-03-14 19:50
Will do! Thanks

**Comment by BlayZin** [comment] 2018-03-17 10:52
I tried it for some Days and it seems to be fixed now!

**Closed** 2018-03-17 11:16 UTC
