### ISSUE TITLE
Reconnection loop.

### ISSUE THREAD

**Issue by crimzind** [phineas05/discord-rich-presence-plex#47] opened 2022-07-11 09:19 UTC
I'm stuck in a loop, not sure how to resolve it.

```
[11-07-2022 05:14:49 AM] [INFO] [CRIM/20264] Connected to Plex Media Server "CRIM"
[11-07-2022 05:14:49 AM] [INFO] [CRIM/20264] Listening for alerts from user "CrimzinD"
[11-07-2022 05:15:10 AM] [ERROR] [CRIM/20264] Connection to Plex lost: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
[11-07-2022 05:15:10 AM] [DEBUG] Attempt to disconnect Discord IPC Pipe while not connected
[11-07-2022 05:15:10 AM] [INFO] [CRIM/20264] Stopped listening for alerts
[11-07-2022 05:15:10 AM] [ERROR] [CRIM/20264] Reconnecting
[11-07-2022 05:15:10 AM] [INFO] [CRIM/20264] Signing into Plex
[11-07-2022 05:15:10 AM] [INFO] [CRIM/20264] Signed in as Plex user "CrimzinD"
[11-07-2022 05:15:10 AM] [INFO] [CRIM/20264] Connecting to Plex Media Server "CRIM"
[11-07-2022 05:16:14 AM] [INFO] [CRIM/20264] Connected to Plex Media Server "CRIM"
```
This pattern just repeats.

**Comment by phineas05** [comment] 2022-08-25 17:17
Duplicate of #48

**Closed by phineas05** 2022-08-25 17:17 UTC
Labels: duplicate
